### ISSUE TITLE
Broken link in a `description` field in `polymorphism` example

### ISSUE THREAD

**Issue by kanadgupta** [readmeio/oas-examples#48]
We've disabled issues for the `api-explorer` repo, so this link 404s: https://github.com/readmeio/api-explorer/issues/495

https://github.com/readmeio/oas-examples/blob/d4457cbdce9d04e5855895fe01500b5b53220938/3.0/json/polymorphism.json#L680

https://github.com/readmeio/oas-examples/blob/d4457cbdce9d04e5855895fe01500b5b53220938/3.0/yaml/polymorphism.yaml#L483

**Comment by erunion** [comment]
Removed in fd3096b1272e468738a6d43de72e46fc61ce18d5
